### ISSUE TITLE
Localized product attributes are not imported correctly

### ISSUE THREAD

**Issue by clicktrend** [Agence-DnD/PIMGento-2#37]
My csv file contains columns like

> description-de_DE-ecommerce 
description-en_US-ecommerce
name-de_DE-ecommerce
name-en_US-ecommerce
price-de_DE-ecommerce-EUR
price-de_DE-ecommerce-USD
price-en_US-ecommerce-EUR
price-en_US-ecommerce-USD

during import "columPrefix" which exists more than one time (description, name, price,...) the [values array](https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L486) gets overriden with the next column in the foreach loop. So the values array takes always the last column. In my example my values array contains

> description-en_US-ecommerce
name-en_US-ecommerce
price-en_US-ecommerce-USD

My magento shop setup is localized with "de_DE".

**Comment by magentix** [comment]
Hi,

Thanks for report. We will fix this on Monday June 20, 2016.

**Comment by magentix** [comment]
Hi,

This has been fixed in release 100.0.11

We need default column for store 0 but we were looking for "ecommerce-de_DE" instead of "de_DE-ecommerce".

So values for store and admin were not setted correctly.

**Comment by magentix** [comment]
@clicktrend

Is it ok for you?

**Comment by clicktrend** [comment]
Unfortunately not! Of course you have found a bug but does not solve my problem. The localized fields (name, description and price) are blank after import.

The error is at the lines [488](https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L488) and [496](https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L496).

I have a fix which is not so good:

Line 488:
```
if(!isset($values[0][$columnPrefix])) { 
    $values[0][$columnPrefix] = $column; 
}
```
and line 496:
```
if(!isset($values[$store['store_id']][$columnPrefix])) { 
    $values[$store['store_id']][$columnPrefix] = $column; 
}
```
This solves my problem but it's not correct because other localized fields will be ignored.

**Comment by shavounet** [comment]
I don't know if the test case is exactly the same or not, but here is my issue : 
- The default value for product attribute is not correctly set ; it uses the last imported locale. It does not impact the value for each store view (so frontend seems safe), but in backoffice, the default value are used in product grid.
- What happens is that the [last locale is used as a default value](https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L548), due to setting `$value[0][$columnPrefix] = $column` at each iteration
- One of main problem issue with that is when the last local too complex, it's hard to find one product in particular in BO ; another problem is using multiple imports with different locales & products, the default result may be inconsistent...
- Proposed fix : in the following "stores" loop, set the default value matching the default store, and if not set just after, set `$value[0]`(bonus point for a warning log in this case ;-) )

**Comment by floplus** [comment]
I can confirm that this issue still exists. 
For each "column" in an import the last occuring column from the entities tmp table in [Pimgento\Product\Model\Factory\Import->setValues](https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L584)

Investigating a fix...

**Comment by magentix** [comment]
Hi,

This issue has been corrected with MR #116 

You can install last release :)

**Comment by HisakaKoji** [comment]
THE FIELD "DESCRIPTION-EN_US-ECOMMERCE" DOES NOT EXIST
The issue still remains in akeneo 2.0.
